name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}
    
    - name: Zip Lambda function
      run: cd src && zip ../function.zip handler.js && cd ..
    
    - name: Deploy to AWS Lambda
      run: |
        FUNCTION_NAME="lambda-template"
        ZIP_FILE="fileb://function.zip"

        # Try to update the function code.
        UPDATE_OUTPUT=$(aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file $ZIP_FILE 2>&1)

        # If the update-function-code command failed because the function does not exist, create the function.
        if [[ $UPDATE_OUTPUT == *"ResourceNotFoundException"* ]]; then
          aws lambda create-function --function-name $FUNCTION_NAME \
            --zip-file $ZIP_FILE \
            --handler handler.handler \
            --runtime nodejs14.x \
            --role arn:aws:iam::ACCOUNT_ID:role/service-role/YourLambdaExecutionRole
        fi
